# Generated by Django 6.0.6 on 2026-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_coinrewardlog_dailyloginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='retailer_status',
            field=models.CharField(choices=[('none', 'Not Eligible'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
