# Generated by Django 6.0.6 on 2026-07-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_customerprofile_retailer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='super_stockist_status',
            field=models.CharField(choices=[('none', 'Not Eligible'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='promotorprofile',
            name='wholesale_status',
            field=models.CharField(choices=[('none', 'Not Eligible'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='subdealerprofile',
            name='distributor_status',
            field=models.CharField(choices=[('none', 'Not Eligible'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', max_length=10),
        ),
    ]
