# Generated by Django 6.0.6 on 2026-08-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_dealerprofile_super_stockist_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jewelryorder',
            index=models.Index(fields=['user_id', 'created_at'], name='accounts_je_user_id_667af4_idx'),
        ),
    ]
