# Generated by Django 6.0.6 on 2026-08-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_coinrecharge_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='lifetime_coins_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='lifetime_recharge_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='lifetime_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
