# Generated by Django 6.0.6 on 2026-08-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_commissionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrecharge',
            name='commission_level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinrecharge',
            name='entry_type',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='credit', max_length=10),
        ),
        migrations.AddField(
            model_name='coinrecharge',
            name='related_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_entries', to='accounts.jewelryorder'),
        ),
        migrations.AddField(
            model_name='coinrecharge',
            name='source',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('commission', 'Commission'), ('purchase', 'Purchase')], default='recharge', max_length=20),
        ),
        migrations.AlterField(
            model_name='coinrecharge',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('commission', 'Commission'), ('purchase', 'Purchase'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='CommissionLog',
        ),
    ]
