# Generated by Django 6.0.6 on 2026-08-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_coinrecharge_commission_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinrecharge',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coinrecharge',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI'), ('netbanking', 'Netbanking'), ('wallet', 'Wallet'), ('commission', 'Commission'), ('purchase', 'Purchase'), ('admin', 'BBTEAM'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='coinrecharge',
            name='source',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('commission', 'Commission'), ('purchase', 'Purchase'), ('admin_credit', 'BBTEAM Credit')], default='recharge', max_length=20),
        ),
    ]
