# Generated by Django 6.0.6 on 2026-08-06 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_coinrecharge_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPayMandate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_day', models.PositiveIntegerField()),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authenticated', 'Authenticated'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('halted', 'Halted')], default='created', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('next_charge_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autopay_mandate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
