# Generated by Django 6.0.6 on 2026-08-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_autopaymandate'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopaymandate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
