# Generated by Django 6.0.6 on 2026-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_autopaymandate_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopaymandate',
            name='last_charge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autopaymandate',
            name='last_charge_error',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autopaymandate',
            name='last_charge_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='autopaymandate',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10),
        ),
    ]
