# Generated by Django 6.0.6 on 2026-08-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_autopaymandate_last_charge_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='jewelryorder',
            index=models.Index(fields=['created_at'], name='accounts_je_created_ce341d_idx'),
        ),
    ]
