# Generated by Django 6.0.6 on 2026-08-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_jewelryorder_accounts_je_created_ce341d_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autopaymandate',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profileupdaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('dealer', 'Dealer'), ('sub_dealer', 'Sub Dealer'), ('promotor', 'Promotor'), ('customer', 'Customer')], db_index=True, default='dealer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['created_by'], name='accounts_ad_created_6f8cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='coinrecharge',
            index=models.Index(fields=['status', 'source', 'commission_level'], name='accounts_co_status_4534ca_idx'),
        ),
        migrations.AddIndex(
            model_name='coinrecharge',
            index=models.Index(fields=['user', 'status', 'source'], name='accounts_co_user_id_cb963a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['assigned_promotor'], name='accounts_cu_assigne_aa2cf8_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['created_by'], name='accounts_cu_created_7ad3ce_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerprofile',
            index=models.Index(fields=['assigned_admin'], name='accounts_de_assigne_926656_idx'),
        ),
        migrations.AddIndex(
            model_name='promotorprofile',
            index=models.Index(fields=['assigned_sub_dealer'], name='accounts_pr_assigne_0d002f_idx'),
        ),
        migrations.AddIndex(
            model_name='subdealerprofile',
            index=models.Index(fields=['assigned_dealer'], name='accounts_su_assigne_b7c31a_idx'),
        ),
    ]
