# Generated by Django 6.0.6 on 2026-08-14 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_jewelryproduct_low_stock_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockNotifyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='coinrequest',
            index=models.Index(fields=['requested_to', 'status', 'created_at'], name='accounts_co_request_8e5671_idx'),
        ),
        migrations.AddField(
            model_name='stocknotifyrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_requests', to='accounts.jewelryproduct'),
        ),
        migrations.AddField(
            model_name='stocknotifyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_notify_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='stocknotifyrequest',
            unique_together={('product', 'user')},
        ),
    ]
