# Generated by Django 6.0.6 on 2026-08-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_stocknotifyrequest_alter_user_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='promotorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='subdealerprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='jewelryproductimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='jewelry_products/'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['dob'], name='accounts_ad_dob_c02075_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['anniversary_date'], name='accounts_ad_anniver_56cb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['dob'], name='accounts_cu_dob_414261_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['anniversary_date'], name='accounts_cu_anniver_d80eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprofile',
            index=models.Index(fields=['created_at'], name='accounts_cu_created_eea5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerprofile',
            index=models.Index(fields=['dob'], name='accounts_de_dob_6d5836_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerprofile',
            index=models.Index(fields=['anniversary_date'], name='accounts_de_anniver_7a04be_idx'),
        ),
        migrations.AddIndex(
            model_name='dealerprofile',
            index=models.Index(fields=['created_at'], name='accounts_de_created_c76a59_idx'),
        ),
        migrations.AddIndex(
            model_name='promotorprofile',
            index=models.Index(fields=['dob'], name='accounts_pr_dob_187f53_idx'),
        ),
        migrations.AddIndex(
            model_name='promotorprofile',
            index=models.Index(fields=['anniversary_date'], name='accounts_pr_anniver_0aa48f_idx'),
        ),
        migrations.AddIndex(
            model_name='promotorprofile',
            index=models.Index(fields=['created_at'], name='accounts_pr_created_255723_idx'),
        ),
        migrations.AddIndex(
            model_name='subdealerprofile',
            index=models.Index(fields=['dob'], name='accounts_su_dob_18a397_idx'),
        ),
        migrations.AddIndex(
            model_name='subdealerprofile',
            index=models.Index(fields=['anniversary_date'], name='accounts_su_anniver_1d7f71_idx'),
        ),
        migrations.AddIndex(
            model_name='subdealerprofile',
            index=models.Index(fields=['created_at'], name='accounts_su_created_b06855_idx'),
        ),
    ]
