# Generated by Django 6.0.6 on 2026-09-02 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_adminprofile_pincode_customerprofile_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('dealer', 'Dealer'), ('sub_dealer', 'Sub Dealer'), ('promotor', 'Promotor'), ('customer', 'Customer'), ('shop', 'Shop')], db_index=True, default='dealer', max_length=20),
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(blank=True, max_length=10, null=True)),
                ('shop_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('street_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('shop_type', models.CharField(choices=[('live', 'Physical Shop'), ('virtual', 'Virtual Shop')], default='live', max_length=10)),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=15, null=True)),
                ('msme_no', models.CharField(blank=True, max_length=25, null=True)),
                ('shop_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shops', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['created_by'], name='accounts_sh_created_a048bd_idx'), models.Index(fields=['shop_type'], name='accounts_sh_shop_ty_826940_idx')],
            },
        ),
    ]
