# Generated by Django 6.0.6 on 2026-09-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_alter_user_role_shopprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelryproduct',
            name='gift_subcategory',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jewelryproduct',
            name='gift_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='category',
            field=models.CharField(choices=[('goldcoin', 'Gold Coin'), ('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bangles', 'Bangles'), ('bracelets', 'Bracelets'), ('earrings', 'Earrings'), ('chains', 'Chains'), ('pendants', 'Pendants'), ('mangalsutra', 'Mangalsutra'), ('maangtikka', 'Maang Tikka'), ('anklets', 'Anklets'), ('nosepin', 'Nose Pin'), ('toerings', 'Toe Rings'), ('cufflinks', 'Cufflinks'), ('brooches', 'Brooches'), ('tiepins', 'Tie Pins'), ('coins', 'Coins')], max_length=20),
        ),
        migrations.AlterField(
            model_name='jewelryproduct',
            name='wedding_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
